spring:
  application:
    name: spring-data-jpa
  datasource:
    username: spring-data-jpa
    password: spring-data-jpa
    url: jdbc:postgresql://localhost:5432/spring-data-jpa_DB
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update